"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import cloudinary
import dj_database_url
from django.urls import reverse_lazy

BASE_DIR = Path(__file__).resolve().parent.parent

APP_ENVIRONMENT = os.getenv('APP_ENVIRONMENT')

SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = False if APP_ENVIRONMENT else True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'theworldofbooks.herokuapp.com',
]

INSTALLED_APPS = [
    # DJANGO APPS
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # THIRD PARTY APPS
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # MY APPS
    'my_project.common',
    'my_project.accounts',
    'my_project.library',
    'my_project.offer',
]

MIDDLEWARE = [
    'my_project.middlewares.handle_server_internal_error',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'templates', 'allauth')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_project.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'project_db',
        'USER': 'postgres',
        'PASSWORD': '1123QwER',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

db_from_env = dj_database_url.config()
DATABASES['default'].update(db_from_env)

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.WorldOfBooksUser'

AUTHENTICATION_BACKENDS = [
    'my_project.accounts.backend.EmailOrUsernameModelBackend',
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 6

ACCOUNT_ADAPTER = 'my_project.accounts.adapter.MyAccountAdapter'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

ACCOUNT_SIGNUP_REDIRECT_URL = reverse_lazy('show_home')

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

DATE_FORMAT = 'd N Y'

USE_L10N = False

BASE_DIR_2 = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS = (
    BASE_DIR / 'static',
)

cloudinary.config(
    cloud_name="hvumptw7s",
    api_key="331815575835463",
    api_secret="56veOLp5yHF6WbsQZSWinOggStE",
    secure=True
)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'theworldofbooks.project@gmail.com'
EMAIL_HOST_PASSWORD = 'lfmnleybhzboeutj'

LOGS_DIR = BASE_DIR / 'Logs'

try:
    os.mkdir(LOGS_DIR)
except:
    pass

LOGIN_LEVEL = "DEBUG" if DEBUG else "ERROR"
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{asctime} [{levelname}] {message}',
            'style': '{',
        },
        'verbose': {
            'format': '{asctime} [{levelname}] {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',

        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'Log.txt',
            'formatter': 'verbose',
        },
    },
    'root': {'handler': ['console', 'file'],
             'level': LOGIN_LEVEL},
    'loggers': {
        'django.db.backends': {
            'level': 'DEBUG' if DEBUG else 'ERROR',
            'handlers': ['console'] if DEBUG else ['file'],
        },
    },
}
