# Generated by Django 4.0.3 on 2022-03-25 16:05

import django.core.validators
from django.db import migrations, models
import my_project.common.helpers.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(2), my_project.common.helpers.custom_validators.OnlyLetterValidator()]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(2), my_project.common.helpers.custom_validators.OnlyLetterValidator()]),
        ),
        migrations.AlterField(
            model_name='sensitiveinformation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(9), my_project.common.helpers.custom_validators.OnlyNumberValidator()]),
        ),
    ]
