# Generated by Django 4.0.3 on 2022-03-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.AddField(
            model_name='sensitiveinformation',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
