# Generated by Django 4.0.3 on 2022-03-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_sensitiveinformation_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
