# Generated by Django 4.0.3 on 2022-04-05 08:11

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_worldofbooksuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worldofbooksuser',
            options={'ordering': [django.db.models.functions.text.Lower('username')]},
        ),
    ]
