# Generated by Django 4.0.3 on 2022-04-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_worldofbooksuser_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensitiveInformation',
            new_name='ContactForm',
        ),
    ]
