# Generated by Django 4.0.3 on 2022-04-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worldofbooksuser',
            options={},
        ),
    ]
