# Generated by Django 4.0.3 on 2022-03-31 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0013_remove_offer_recipient_remove_offer_recipient_books_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_accept', models.BooleanField(default=True)),
                ('recipient_accept', models.BooleanField(default=False)),
                ('deal', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_offer', to=settings.AUTH_USER_MODEL)),
                ('recipient_books', models.ManyToManyField(related_name='wanted', to='library.book')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_offer', to=settings.AUTH_USER_MODEL)),
                ('sender_books', models.ManyToManyField(related_name='offered', to='library.book')),
            ],
        ),
    ]
