# Generated by Django 4.0.3 on 2022-04-01 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offer_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='sender_accept',
            new_name='accept',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='recipient_accept',
        ),
        migrations.AddField(
            model_name='offer',
            name='previous_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_offer', to='offer.offer'),
        ),
    ]
