# Generated by Django 4.0.3 on 2022-04-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_alter_offer_is_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='is_accept',
            field=models.BooleanField(null=True),
        ),
    ]
