# Generated by Django 4.0.3 on 2022-04-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_alter_offer_is_accept'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-received_date']},
        ),
        migrations.AddField(
            model_name='offer',
            name='received_date',
            field=models.DateTimeField(auto_now_add=True, default='2022-04-01 19:00'),
            preserve_default=False,
        ),
    ]
