# Generated by Django 4.0.3 on 2022-03-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
