# Generated by Django 4.0.3 on 2022-03-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_notification_is_answered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-received_date']},
        ),
    ]
