# Generated by Django 4.0.3 on 2022-03-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Change owner', 'Change Owner'), ('Liked', 'Liked'), ('Reviewed', 'Reviewed'), ('Offered', 'Offered')], max_length=12),
        ),
    ]
