# Generated by Django 4.0.3 on 2022-03-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Change owner', 'Change Owner'), ('Liked', 'Liked'), ('Disliked', 'Disliked'), ('Reviewed', 'Reviewed'), ('Offered', 'Offered')], max_length=12),
        ),
    ]
