# Generated by Django 4.0.3 on 2022-03-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='book',
            new_name='subject',
        ),
    ]
