# Generated by Django 4.0.3 on 2022-03-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_rename_book_notification_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='subject',
            new_name='book',
        ),
    ]
