# Generated by Django 4.0.3 on 2022-03-30 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0012_alter_offer_recipient_books_alter_offer_sender_books'),
        ('common', '0007_rename_subject_notification_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='library.offer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Change owner', 'Change Owner'), ('Liked', 'Liked'), ('Disliked', 'Disliked'), ('Reviewed', 'Reviewed'), ('Offered', 'Offered'), ('Counter offered', 'C Offered')], max_length=15),
        ),
    ]
