# Generated by Django 4.0.3 on 2022-03-31 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0014_delete_offer'),
        ('common', '0009_alter_notification_offer_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='massage',
            field=models.TextField(default='Old notifications'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='library.book'),
        ),
    ]
